eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: service-zull

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: CONSUMER-SERVICE-RIBBON
    api-b:
      path: /api-b/**
      serviceId: CONSUMER-SERVICE-FEIGN


